CREATE DATABASE IF NOT EXISTS PTFMS;
USE PTFMS;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100),
    USER_TYPE ENUM('MANAGER', 'OPERATOR') NOT NULL
);